# Generated by Django 3.2.3 on 2021-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=40)),
                ('sp', models.IntegerField()),
                ('nq', models.IntegerField()),
                ('dw', models.IntegerField()),
            ],
        ),
    ]
